apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo-sm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          policy.kyverno.io/synchronize: enable
  template:
    metadata:
      name: '{{name}}-helper'
    spec:
      project: workload-infra
      source:
        repoURL: {{repoURL}}
        targetRevision: main
        path: "helper"
      destination:
        server: '{{server}}'
        namespace: podinfo-helper
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
