apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secret-aks-preprod
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: sync-secret-aks-preprod
    match:
      any:
      - resources:
          names:
          - "aks-preprod*"
          kinds:
          - Secret
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - default
          - kube-public
          - kyverno
    context:
    - name: name
      variable:
        value: "{{ request.object.metadata.name }}"
    - name: ca
      variable: 
        value: "{{ request.object.data.\"certificate-authority\" }}"
        jmesPath: 'base64_decode(@)'
    - name: cert
      variable: 
        value: "{{ request.object.data.\"client-certificate\" }}"
        jmesPath: 'base64_decode(@)'
    - name: key
      variable: 
        value: "{{ request.object.data.\"client-key\" }}"
        jmesPath: 'base64_decode(@)'
    - name: server
      variable: 
        value: "{{ request.object.data.\"server\" }}"
        jmesPath: 'base64_decode(@)'
    - name: aksName
      variable:
        value: "{{ replace_all(name, 'aks-', '') }}"
        jmesPath: 'to_string(@)'
    generate:
      kind: Secret
      apiVersion: v1
      name: "{{ aksName }}"
      namespace: argocd
      synchronize: true
      data:
        kind: Secret
        metadata:
          labels:
            argocd.argoproj.io/secret-type: cluster
            clusterType: "aks"
            env: "preprod"
            prometheus: "true"
            podinfo: "true"
            k8s-dashboard : "false"
            opa: "false"
            cert-manager: "false"
        stringData:
          name: "{{ aksName }}"
          server: "{{ server }}" 
          config: |
            {
              "tlsClientConfig": {
                "insecure": false,
                "caData": "{{ ca }}",
                "certData": "{{ cert }}",
                "keyData": "{{ key }}"
              }
            }
