apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - values:
                    component: prometheus
                    branchOrTag: dev
          - clusters:
              selector:
                matchExpressions:
                  - key: '{{values.component}}'
                    operator: In
                    values: 
                    - "true"
                matchLabels:
                  policy.kyverno.io/synchronize: enable
                  env: dev
  template:
    metadata:
      name: '{{values.component}}-{{name}}'
      labels: 
        component: '{{values.component}}'
        component-version: '{{values.branchOrTag}}'
        cluster-id: '{{name}}'
    spec:
      project: workload-dev
      source:
        repoURL: https://github.com/joaquinrz/cluster-addons-{{values.component}}.git
        targetRevision: '{{values.branchOrTag}}'
        path: deploy
      destination:
        server: https://kubernetes.default.svc
        namespace: cluster-addons
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
